env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "import/extensions": "off",
  "semi": ["error", "never"],
  "react/function-component-definition": off,
  "react/prop-types": off,
  "react/no-array-index-key": off,
  "max-len": off,
}
